from typing import Protocol, Any, List, Optional
from .models import RoleProtocol, PermissionProtocol, PermissionCategoryProtocol, RouteProtocol, UserRoleProtocol, PermissionAssignmentProtocol, PermissionRouteProtocol

class RoleServiceProtocol(Protocol):
    async def create_role(self, role_data: Any, session: Any) -> RoleProtocol: ...
    async def get_role(self, role_id: int, session: Any) -> Optional[RoleProtocol]: ...
    async def list_roles(self, session: Any, skip: int = 0, limit: int = 100) -> List[RoleProtocol]: ...
    async def update_role(self, role_id: int, role_data: Any, session: Any) -> Optional[RoleProtocol]: ...
    async def delete_role(self, role_id: int, session: Any) -> bool: ...
    async def add_role_permission(self, role_id: int, permission_id: int, session: Any) -> PermissionAssignmentProtocol: ...
    async def list_role_permissions(self, role_id: int, session: Any) -> List[PermissionProtocol]: ...
    async def delete_role_permission(self, role_id: int, permission_id: int, session: Any) -> bool: ...
    async def assign_user_role(self, user_id: int, role_id: int, session: Any) -> UserRoleProtocol: ...
    async def list_user_roles(self, user_id: int, session: Any) -> List[RoleProtocol]: ...
    async def remove_user_role(self, user_id: int, role_id: int, session: Any) -> bool: ...

class PermissionServiceProtocol(Protocol):
    async def create_category(self, category_data: Any, session: Any) -> PermissionCategoryProtocol: ...
    async def list_categories(self, session: Any, skip: int = 0, limit: int = 100) -> List[PermissionCategoryProtocol]: ...
    async def create_permission(self, permission_data: Any, session: Any) -> PermissionProtocol: ...
    async def get_permission(self, permission_id: int, session: Any) -> Optional[PermissionProtocol]: ...
    async def list_permissions(self, session: Any, skip: int = 0, limit: int = 100) -> List[PermissionProtocol]: ...
    async def update_permission(self, permission_id: int, permission_data: Any, session: Any) -> Optional[PermissionProtocol]: ...
    async def delete_permission(self, permission_id: int, session: Any) -> bool: ...
    async def add_permission_route(self, permission_id: int, route_id: int, session: Any) -> PermissionRouteProtocol: ...
    async def assign_user_permission(self, user_id: int, permission_id: int, session: Any) -> PermissionAssignmentProtocol: ...
    async def list_user_permissions(self, user_id: int, session: Any) -> List[PermissionProtocol]: ...
    async def remove_user_permission(self, user_id: int, permission_id: int, session: Any) -> bool: ...

class AccessServiceProtocol(Protocol):
    async def check_user_access(self, user_id: int, route_path: str, method: str, session: Any) -> bool: ...
